<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>首页左侧导航</title>
<link rel="stylesheet" type="text/css"
	href="__PUBLIC__/Admin/css/public.css" />
<script type="text/javascript" src="__PUBLIC__/Admin/js/jquery.min.js"></script>
<!-- <script type="text/javascript" src="__PUBLIC__/Admin/js/public.js" ></script> -->
<head></head>

<body id="bg">
	<!-- 左边节点 -->
	<div class="container">

		<div class="leftsidebar_box">
			<a href="{:U('Admin/Index/main')}" " target="main"><div class="line">
					<img src="__PUBLIC__/Admin/img/coin01.png" />&nbsp;&nbsp;首页
				</div></a>
			<!-- <dl class="system_log">
			<dt><img class="icon1" src="__PUBLIC__/Admin/img/coin01.png" /><img class="icon2"src="__PUBLIC__/Admin/img/coin02.png" />
				首页<img class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img class="icon4" src="__PUBLIC__/Admin/img/coin20.png" /></dt>
		</dl> -->
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coin03.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coin04.png" /> 网站管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/User/user')}" target="main">管理员管理</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coin05.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coin06.png" /> 公共管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/Adv/banner')}" target="main">广告管理</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/Adv/opinion')}" target="main">意见反馈</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coin07.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coin08.png" /> 会员管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/Vip/vip')}" target="main">会员管理</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coin10.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coin09.png" /> 行家管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						href="{:U('Admin/Expert/connoisseur')}" target="main" class="cks">行家管理</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coin11.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coin12.png" /> 话题管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						href="{:U('Admin/Talks/index')}" target="main" class="cks">话题管理</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coin14.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coin13.png" /> 心愿管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>

				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/Wish/index')}" target="main">心愿管理</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>

			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coin15.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coin16.png" /> 约见管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/Meet/index')}" target="main">约见管理</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coin17.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coin18.png" /> 收支管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/Pay/index')}" target="main">收支管理</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coin17.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coin18.png" /> 红包管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/Red/make')}" target="main">创建记录</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/Red/get')}" target="main">领取记录</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						class="cks" href="{:U('Admin/Red/share')}" target="main">分享记录</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="__PUBLIC__/Admin/img/coinL1.png" /><img
						class="icon2" src="__PUBLIC__/Admin/img/coinL2.png" /> 系统管理<img
						class="icon3" src="__PUBLIC__/Admin/img/coin19.png" /><img
						class="icon4" src="__PUBLIC__/Admin/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						href="{:U('Admin/System/changePwd')}" target="main" class="cks">修改密码</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="__PUBLIC__/Admin/img/coin111.png" /><img
						class="coin22" src="__PUBLIC__/Admin/img/coin222.png" /><a
						href="{:U('Admin/System/exit')}" class="cks"
						onclick="{if(confirm(&quot;您确定退出吗?&quot;)){return true;}return false;}">退出</a><img
						class="icon5" src="__PUBLIC__/Admin/img/coin21.png" />
				</dd>
			</dl>

		</div>

	</div>
</body>

</html>
